jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
  mvc:
    resources:
      static-locations: src/main/webapp/
  #    view:
  #      suffix: .html
  datasource:
    url: ENC(t7pvzQpjkYPyXsrWRmsWExW1/T7fXy6Y3ZE7RHfwp0D/1OCQwPo7elS3apb3/lFzinA45L6AnQ/hWF/N/qmRIUYDhBo0NsFp/nEbjwea98I=)
    username: ENC(7a7iff3s31ZM7MSM5Nm1KkhXC8Q+72gtemO5l+Tx/yZ8x90CM9xP1NwNpOgVGKkK)
    password: ENC(HsoJf0PUii70PHtTSr0snzmDZNLWZ4UMfKmfN4rPEllDSw8weU5KFqOPVSWNnrWM)
    driver-class-name: org.mariadb.jdbc.Driver

  jwt:
    secret: ${JWT_SECRET}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-name: letthinggo
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope: profile,email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-name: letthinggo
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: profile_nickname,account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs