spring:
  mvc:
    resources:
      static-locations: src/main/webapp/
#    view:
#      suffix: .html
  datasource:
    url: jdbc:mariadb://52.79.168.177:3306/ltg
    username: ltg
    password: ltg.qwe123
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:h2:tcp://localhost/~/testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jwt:
    secret: 502dddd2c8b1621fef4ed62bb03beba62e4cad4e59708539aa0809ca92152e9dc8842dac8a6b2552fe73437d9fed46f1e7c0b4b8da843cafb1771264c021f1ea
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 54389455163-0fkv2c91d7ktvp7jtpqr182ncfk2kg27.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: aQPA1fbCMbP9JbfseQ7W
            client-secret: VBNasq4MpX
            authorization-grant-type: authorization_code
            client-name: letthinggo
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            redirect-uri: http://52.79.168.177:8080/login/oauth2/code/naver
            scope: profile,email
          kakao:
            client-id: 221e1309d7005efd50b77c126052055e
            client-secret: s5bZL3JJUIPUeAyrzDm6oYGM99bGZ79W
            authorization-grant-type: authorization_code
            #client-authentication-method: client_secret_post
            client-name: letthinggo
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: http://52.79.168.177:8080/login/oauth2/code/kakao
            scope: profile_nickname,account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#            user-terms-info-uri: https://openapi.naver.com/v1/nid/agreement
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # OpenID Connect 로 인가서버와 통신하지 않을 경우

  jpa:
    hibernate:
      ddl-auto: none #validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs